version: '2'

services: 
  drupal: 
    image: drupal
    ports: 
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profies:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  db:
    image: postgres
    volumes: 
      - db-data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=foobar 
volumes: 
  drupal-modules:
