version: "3"
services:
  drupal:
    image: "drupalology"
    build: .
    ports:
      - "80:5342"

  db:
    image: "postgres:latest"
    volumes: 
      - drupal-data:/var/lib/postgres_drupal
    environment:
      - POSTGRES_PASSWORD=foster

volumes:
  drupal-data:
